# ~/.config/zsh/starship.toml

format = """
$directory$git_branch$git_status$cmd_duration$line_break$character
"""
add_newline = true

[directory]
style = "blue"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[git_branch]
symbol = " "
style = "yellow"
truncation_length = 16
truncation_symbol = "…"

[git_status]
disabled = false  # Disabled by default for non-Git directories
style = "red"
conflicted = "⚔️ "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
modified = "modified ${count}"
staged = "staged ${count}"
deleted = "deleted ${count}"
untracked = "untracked ${count}"
stashed = "stashed ${count}"
renamed = "renamed ${count}"

[cmd_duration]
min_time = 1000  # Show only if > 1s
format = "took [$duration]($style)"
style = "dimmed white"
